development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: kirka121
  :password: C45tt6KL32
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: kirka121
  :password: C45tt6KL32
  :enable_starttls_auto: true